version: '{build}'
branches:
  only:
  - ui-localisation
  - translation
os: Visual Studio 2015
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
environment:
  PATH: C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    git submodule init

    git submodule update


    nuget restore source\KanColleViewer.sln -PackagesDirectory source\packages
build:
  project: source\KanColleViewer.sln
  publish_nuget: false
  verbosity: minimal
after_build:
- cmd: >-
    7z a KanColleViewer.zip 
    %APPVEYOR_BUILD_FOLDER%\source\Grabacr07.KanColleViewer\bin\Release\*.dll
    %APPVEYOR_BUILD_FOLDER%\source\Grabacr07.KanColleViewer\bin\Release\KanColleViewer.exe
    %APPVEYOR_BUILD_FOLDER%\source\Grabacr07.KanColleViewer\bin\Release\KanColleViewer.exe.config

    7z a KanColleViewer.zip 
    %APPVEYOR_BUILD_FOLDER%\source\Grabacr07.KanColleViewer\bin\Release\en
    %APPVEYOR_BUILD_FOLDER%\source\Grabacr07.KanColleViewer\bin\Release\ko-KR
    %APPVEYOR_BUILD_FOLDER%\source\Grabacr07.KanColleViewer\bin\Release\zh-CN

    7z a 
    -xr!*.pdb 
    -xr!*.xml
    -xr!*.config
    -xr!ExPlugin.*
    KanColleViewer.zip 
    %APPVEYOR_BUILD_FOLDER%\source\Grabacr07.KanColleViewer\bin\Release\Plugins
artifacts:
- path: KanColleViewer.zip
  name: KanColleViewer
deploy:
- provider: FTP
  beta: true
  protocol: ftps
  host: koumakan.jp
  username: $(ftpuser)
  password: $(ftppassword)
  folder: $(appveyor_repo_branch)-$(appveyor_build_version)
  artifact: KanColleViewer.zip